CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    username VARCHAR(120) NOT NULL,
    previous_status VARCHAR(20),
    new_status VARCHAR(20) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_status_history_order_id ON order_status_history(order_id);
CREATE INDEX idx_order_status_history_user_id ON order_status_history(user_id);

CREATE TABLE pc_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    username VARCHAR(120) NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    budget NUMERIC(12, 2) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(16) NOT NULL,
    performance_estimate VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pc_configurations_user_id ON pc_configurations(user_id);
CREATE INDEX idx_pc_configurations_created_at ON pc_configurations(created_at);

CREATE TABLE pc_configuration_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuration_id BIGINT NOT NULL REFERENCES pc_configurations(id) ON DELETE CASCADE,
    product_id BIGINT,
    component_type VARCHAR(50) NOT NULL,
    product_name VARCHAR(180) NOT NULL,
    brand VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC(12, 2) NOT NULL,
    score NUMERIC(5, 2) NOT NULL DEFAULT 0
);

CREATE INDEX idx_pc_configuration_items_configuration_id ON pc_configuration_items(configuration_id);
CREATE INDEX idx_pc_configuration_items_product_id ON pc_configuration_items(product_id);

CREATE TABLE compatibility_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuration_id BIGINT NOT NULL REFERENCES pc_configurations(id) ON DELETE CASCADE,
    check_type VARCHAR(100) NOT NULL,
    check_status VARCHAR(30) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    checked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_compatibility_checks_configuration_id ON compatibility_checks(configuration_id);

CREATE TABLE recommendation_alternatives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuration_id BIGINT NOT NULL REFERENCES pc_configurations(id) ON DELETE CASCADE,
    alternative_type VARCHAR(50) NOT NULL,
    total_price NUMERIC(12, 2) NOT NULL,
    payload_json VARCHAR(10000) NOT NULL
);

CREATE INDEX idx_recommendation_alternatives_configuration_id ON recommendation_alternatives(configuration_id);
