spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URL:jdbc:postgresql://localhost:5432/diploma}
    username: ${ORDER_DB_USERNAME:diploma}
    password: ${ORDER_DB_PASSWORD:diploma}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    table: flyway_schema_history_order
    baseline-on-migrate: true
    baseline-version: 0
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  kafka:
    enabled: ${ORDER_KAFKA_ENABLED:true}
    topics:
      order-created: ${ORDER_CREATED_TOPIC:order.created.v1}
      order-status-changed: ${ORDER_STATUS_CHANGED_TOPIC:order.status.changed.v1}
