CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    description VARCHAR(2000),
    brand VARCHAR(120) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    in_stock BOOLEAN NOT NULL,
    stock_quantity INTEGER NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_price ON products(price);
CREATE INDEX idx_products_category_id ON products(category_id);

INSERT INTO categories(name, slug) VALUES
('Processors', 'processors'),
('Graphics Cards', 'graphics-cards'),
('Memory', 'memory');

INSERT INTO products(name, description, brand, price, currency, in_stock, stock_quantity, category_id) VALUES
('Ryzen 7 7800X3D', '8-core gaming CPU', 'AMD', 369.99, 'RUB', TRUE, 20, 1),
('Core i7-14700K', '20-core hybrid desktop CPU', 'Intel', 429.99, 'RUB', TRUE, 15, 1),
('GeForce RTX 4070 Super', 'NVIDIA mid-high GPU', 'NVIDIA', 699.99, 'RUB', TRUE, 10, 2),
('Radeon RX 7800 XT', 'AMD 1440p gaming GPU', 'AMD', 569.99, 'RUB', FALSE, 0, 2),
('DDR5 32GB Kit 6000MHz', '2x16GB memory kit', 'Kingston', 129.99, 'RUB', TRUE, 42, 3);
